name: carby
description: Simple managing of bookings.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  path: ^1.8.0
  package_info_plus: ^1.4.0
  easy_localization: ^3.0.0
  signature: ^5.0.0
  image_picker: ^0.8.4+10
  video_player: ^2.2.19
  google_maps_flutter: ^2.1.3
  flutter_inappwebview: ^5.3.2
  url_launcher: ^6.0.20
  webviewx: ^0.2.1
  flutter_webview_plugin: ^0.4.0
  google_fonts: ^2.3.2
  unicons: ^2.1.0
  permission_handler: ^9.2.0
  geolocator: ^8.2.0
  location: ^4.3.0
  shared_preferences: ^2.0.13
  rating_dialog: ^2.0.4
  firebase_core: ^1.16.0
  firebase_messaging: ^11.3.0
  flutter_local_notifications: ^9.5.2
  webview_flutter: ^2.8.0
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the

# The following section is specific to Flutter.
flutter:

  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
  
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
        - asset: assets/fonts/Jost-Italic.ttf
        - asset: assets/fonts/Jost-Bold.ttf
